version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: macmorning-mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:latest
    container_name: macmorning-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  ingq-be:
    build:
      context: ./ingq
      dockerfile: Dockerfile.local
    container_name: macmorning-be
    ports:
      - "${BE_PORT}:${BE_PORT}"
    env_file: .env
    volumes: 
      - ./ingq:/ingq
      - /ingq/.venv
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "uv sync --frozen --no-cache && uv run uvicorn main:app --port 8000 --host 0.0.0.0 --reload"

  ingq-ai:
    build:
      context: ./ai
      dockerfile: Dockerfile.local
    container_name: macmorning-ai
    ports:
      - "${AI_PORT}:${AI_PORT}"
    env_file: .env
    volumes: 
      - ./ai:/ai
      - /ai/.venv
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "uv sync --frozen --no-cache && uv run uvicorn main:app --port 8080 --host 0.0.0.0 --reload"

volumes:
  redis_data: