version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: macmorning-mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    restart: always
    
  ingq-be:
    build:
      context: ./ingq
      dockerfile: Dockerfile.dev
    container_name: macmorning-be
    ports:
      - "${BE_PORT}:${BE_PORT}"
    env_file: .env
    depends_on:
      - db
    restart: always

  ingq-ai:
    build:
      context: ./ai
      dockerfile: Dockerfile.dev
    container_name: macmorning-ai
    ports:
      - "${AI_PORT}:${AI_PORT}"
    env_file: .env
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: macmorning-nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ingq-be
      - ingq-ai
    restart: always
