version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: macmorning-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    restart: always
    
  ingq-be:
    build:
      context: ./ingq
      dockerfile: Dockerfile
    container_name: macmorning-be
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: always
