from core.setting.load_env import (
    DATABASE_URL,
    MYSQL_DB_NAME,
    MYSQL_HOST,
    MYSQL_PASSWORD,
    MYSQL_PORT,
    MYSQL_USERNAME,
)


class DbConfig:
    MYSQL_USERNAME = MYSQL_USERNAME
    MYSQL_PASSWORD = MYSQL_PASSWORD
    MYSQL_HOST = MYSQL_HOST
    MYSQL_PORT = MYSQL_PORT
    MYSQL_DB_NAME = MYSQL_DB_NAME

    DATABASE_URL = DATABASE_URL


db_config = DbConfig()
