"""is_storage -> is_in_progress

Revision ID: d55929290d1e
Revises: 739db194850e
Create Date: 2025-04-18 23:51:40.051115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd55929290d1e'
down_revision: Union[str, None] = '739db194850e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_in_progress', sa.Boolean(), nullable=False))
    op.drop_column('books', 'is_storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_storage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('books', 'is_in_progress')
    # ### end Alembic commands ###
