"""add book table

Revision ID: 29e04d8bb09e
Revises: 87df881dd7c7
Create Date: 2025-04-18 15:10:13.444173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29e04d8bb09e"
down_revision: Union[str, None] = "87df881dd7c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("genre", sa.JSON(), nullable=False),
        sa.Column("gamemode", sa.Boolean(), nullable=False),
        sa.Column("character", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=36), nullable=False),
        sa.Column("background", sa.String(length=512), nullable=False),
        sa.Column("is_storage", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
