"""Choice Table의 my_choice, is_success Optional로 설정

Revision ID: d92977df563b
Revises: c304ee426d7f
Create Date: 2025-07-19 06:25:37.751632

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd92977df563b'
down_revision: Union[str, None] = 'c304ee426d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choices', 'my_choice',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('choices', 'is_success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choices', 'is_success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('choices', 'my_choice',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
