"""add reason field to Choice

Revision ID: c304ee426d7f
Revises: 2806d95fd554
Create Date: 2025-06-16 11:55:05.571432

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c304ee426d7f'
down_revision: Union[str, None] = '2806d95fd554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choices', 'reason')
    # ### end Alembic commands ###
