"""modify books table field

Revision ID: 739db194850e
Revises: 29e04d8bb09e
Create Date: 2025-04-18 21:06:19.756318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '739db194850e'
down_revision: Union[str, None] = '29e04d8bb09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('books', 'background',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'background',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
