"""add title_img field to Book

Revision ID: 2806d95fd554
Revises: e8a1da4bf3e6
Create Date: 2025-05-20 01:41:15.522309

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2806d95fd554'
down_revision: Union[str, None] = 'e8a1da4bf3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title_img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'title_img')
    # ### end Alembic commands ###
