"""add CheckConstraint in Choice & UniqueConstraint in Story

Revision ID: e8a1da4bf3e6
Revises: 0b6babd9a2b0
Create Date: 2025-04-30 23:38:34.124341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8a1da4bf3e6'
down_revision: Union[str, None] = '0b6babd9a2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_book_page_uc', 'stories', ['book_id', 'page_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_book_page_uc', 'stories', type_='unique')
    # ### end Alembic commands ###
