"""Add users table

Revision ID: 87df881dd7c7
Revises: 
Create Date: 2025-04-04 16:53:02.868751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87df881dd7c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('profile_image', sa.String(length=255), server_default='https://www.gravatar.com/avatar/?d=mp', nullable=True),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', name='provider'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
