"""Add users table

Revision ID: 989b1a68270d
Revises:
Create Date: 2025-04-02 13:55:56.092844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "989b1a68270d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("email", table_name="users")
    op.drop_index("nickname", table_name="users")
    op.drop_index("phone_number", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=64), nullable=True),
        sa.Column("nickname", mysql.VARCHAR(length=10), nullable=False),
        sa.Column(
            "profile_image",
            mysql.VARCHAR(length=255),
            server_default=sa.text("'https://www.gravatar.com/avatar/?d=mp'"),
            nullable=True,
        ),
        sa.Column("username", mysql.VARCHAR(length=10), nullable=False),
        sa.Column("phone_number", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("provider", mysql.ENUM("LOCAL", "GOOGLE"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    op.create_index("phone_number", "users", ["phone_number"], unique=True)
    op.create_index("nickname", "users", ["nickname"], unique=True)
    op.create_index("email", "users", ["email"], unique=True)
    # ### end Alembic commands ###
